id: P006621
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6688
  title: 'རྫ་ཙིག་གཏམ་རྒྱུད།

    '
  author: ''
  volumes:
    f7b3cb6e7e9e43dab0256d6bf5ebadf4:
      image_group_id: I3CN6690
      title: ''
      volume_number: 1
      total_pages: 33
      base_file: v001.txt
